//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SInhVien.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTin
    {
        public int ID { get; set; }
        public int MaSv { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public string SoDienThoaiSV { get; set; }
        public string Lop { get; set; }
        public string Khoa { get; set; }
        public string HoTenChuTro { get; set; }
        public string DiaChiNoiCuTru { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
    }
}
